### ISSUE TITLE
MIDISequencerStep position param question

### ISSUE THREAD

**Issue by ilionic** [cemolcay/MIDISequencer#6]
Hello, more a question than an issue. Trying to wrap head around `position` parameter of `MIDISequencerStep`. Based on docs is not quite clear how it works 

> Position in track, in form of beats.

How can it be translated in musical terms if I'd like various pattern variations, i.e. :

<img width="365" alt="screenshot 2018-01-18 01 29 16" src="https://user-images.githubusercontent.com/1027871/35074617-0779873c-fbef-11e7-9a81-a1dd0b68c4d2.png">

Thanks!

**Comment by ilionic** [comment]
Does `position` 0.25 equal to quarter note?

**Comment by cemolcay** [comment]
Yes, that's right. Every bar and beat represented in double values. A bar's duration is `1.0`, a beat's duration is `1.0 / timeSignature.beats`.
You can check out the example to figure out laying out your steps on a track.
https://github.com/cemolcay/MIDISequencer/blob/master/Example%20iOS/ViewController.swift#L45

**Comment by ilionic** [comment]
Thanks, yes I'v checked example. So assuming it's 16 step sequencer if I put 
```
      steps: [
        MIDISequencerStep(
          note: Note(type: .c, octave: 3),
          position: 0.0,
          duration: 0.5,
          velocity: bassVolume),
        MIDISequencerStep(
          note: Note(type: .d, octave: 4),
          position: 2.0,
          duration: 0.5,
          velocity: bassVolume),
    ]
```
I'd expect pattern to be like:
x------x-------
but instead looks like after second note drops back to beginning of the bar. What am I missing?
Another question, is it possible to change number of steps in track?

**Comment by cemolcay** [comment]
Yes, sequencer sets its duration to its longest track's duration automatically.
You need to add an empty `MIDISequencerStep` at the end of the steps.

``` swift
MIDISequencerStep(
  position: 2.5, 
  duration: 0.5)
```

However, I just released a new version, 0.0.4 for this issue. Now you can set your sequencer's duration by custom bar or step count.
- `sequencer.duration = .auto` is default option, which calculates the longest track's duration, like the versions before.
- `sequencer.duration = .bars(2)` is duration by full bar counts.
- `sequnecer.duration = .steps(16)` is duration by step counts.

Hope it helps!

**Comment by ilionic** [comment]
Thank you for fast update, this is very cool! 
Now I am thinking would be great to have similar API for `MIDISequencerTrack` for polyrhythmic stuff 👍  
Do you think is possible?

**Comment by ilionic** [comment]
I can probably figure it out based on your example and send PR if you like, but quite new to Swift so would take time

**Comment by cemolcay** [comment]
Yeah, sure, feel free to send PRs 👍

**Comment by ilionic** [comment]
Looks like it is limitation of AKSequencer based on https://github.com/audiokit/AudioKit/issues/667
