### ISSUE TITLE
Step callback / clock?

### ISSUE THREAD

**Issue by ilionic** [cemolcay/MIDISequencer#8]
What's the best way getting track / step callback for some visual indication ( calling arbitrary function )?
Found some references in AudioKit using SelectorClock and AKCallbackInstrument. 
Then noticed there is `MIDISequencerCallbackInstrument` but feels like missing some documentation / examples in this area.
Can `MIDISequencerCallbackInstrument` be used to get step callback ( even empty ) or need to setup custom clock?
Thanks!

**Comment by cemolcay** [comment]
Yeah,  `MIDISequencerCallbackInstrument ` was an `AKCallbackInstrument` subclass I was using in the first few versions but later I deprecated it. 

`AKSequencer` has `currentPosition` and `currentRelativePosition` properties to show current step. You can either set an observer to them (not sure) or setup a custom timer like you suggested.

I did the custom timer on my app ChordBud. Just set its interval to `1.0 / sequencer.tempo.bpm` and each tick get the `sequencer.currentRelativePosition.beats` to get the current step.

**Comment by ilionic** [comment]
Custom timer sounds like the way to go! thank you!
